### ISSUE TITLE
As a trainer, I want to keep track on client's exercises

### ISSUE THREAD

**Issue by dhafinrazaq** [AY2021S1-CS2103T-T13-3/tp#120]
Can be exercise type or additional comments
will be displayed in a table

**Comment by dhafinrazaq** [comment]
Can be exercise type or additional comments

**Comment by benclmnt** [comment]
We can implement this as a remark inside `Schedule`.

The remark is for the fitness instructor to add in comments and/or types of exercises done by this client.

We can then display it as part of the client's information
