### ISSUE TITLE
Are we allowing session to exceed more than 1 day? 

### ISSUE THREAD

**Issue by tanweijie123** [AY2021S1-CS2103T-T13-3/tp#155]
Use case: Gym camp, expedition, etc 

Concerns: Today's schedule might need to return period instead of today's start date.

**Comment by benclmnt** [comment]
current implementation only check for invalid duration ( < 0 ), but don't have upper limit yet

**Comment by tanweijie123** [comment]
Allowed. 
Today's schedule already catered for periods for that.
