### ISSUE TITLE
DeleteSession should check for corresponding schedules

### ISSUE THREAD

**Issue by benclmnt** [AY2021S1-CS2103T-T13-3/tp#98]

**Comment by dhafinrazaq** [comment]
A good feature to have. will the implementation be like inside DeleteSessionCommand, iterate through the model's ScheduleList?

**Comment by benclmnt** [comment]
Yes, I propose this implementation:

- `sdel INDEX` : will delete only if there is no schedule tied to that session
- `sdel INDEX f/ true`: will **force** delete all schedule tied to that session and the session itself.

Implementation: 
- Will look for all schedules tied to the corresponding session before deleting the session

**Comment by dhafinrazaq** [comment]
looks good
